// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  lobbyId: __t.u64().primaryKey().name("lobby_id"),
  inviteCode: __t.string().name("invite_code"),
  hostIdentity: __t.option(__t.identity()).name("host_identity"),
  hostName: __t.string().name("host_name"),
  status: __t.string(),
  round: __t.i32(),
  isPublic: __t.bool().name("is_public"),
  openedDoors: __t.array(__t.i32()).name("opened_doors"),
  playerCount: __t.i32().name("player_count"),
  createdAt: __t.timestamp().name("created_at"),
  hostLastSeen: __t.timestamp().name("host_last_seen"),
});
