// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  name: __t.string(),
  lobbyId: __t.u64().name("lobby_id"),
  wx: __t.f32(),
  wz: __t.f32(),
  ry: __t.f32(),
  hp: __t.i32(),
  points: __t.i32(),
  online: __t.bool(),
  alive: __t.bool(),
  downed: __t.bool(),
  spectating: __t.bool(),
  lastSeen: __t.timestamp().name("last_seen"),
  kills: __t.i32(),
  downs: __t.i32(),
});
