// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  puId: __t.u64().primaryKey().name("pu_id"),
  typeIdx: __t.i32().name("type_idx"),
  wx: __t.f32(),
  wz: __t.f32(),
  spawnedAt: __t.timestamp().name("spawned_at"),
});
