// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  msgId: __t.u64(),
  lobbyId: __t.u64(),
  sender: __t.identity(),
  senderName: __t.string(),
  text: __t.string(),
  createdAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const HighScore = __t.object("HighScore", {
  scoreId: __t.u64(),
  name: __t.string(),
  round: __t.i32(),
  points: __t.i32(),
  kills: __t.i32(),
  createdAt: __t.timestamp(),
});
export type HighScore = __Infer<typeof HighScore>;

export const Lobby = __t.object("Lobby", {
  lobbyId: __t.u64(),
  inviteCode: __t.string(),
  hostIdentity: __t.option(__t.identity()),
  hostName: __t.string(),
  status: __t.string(),
  round: __t.i32(),
  isPublic: __t.bool(),
  openedDoors: __t.array(__t.i32()),
  playerCount: __t.i32(),
  createdAt: __t.timestamp(),
  hostLastSeen: __t.timestamp(),
});
export type Lobby = __Infer<typeof Lobby>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  lobbyId: __t.u64(),
  wx: __t.f32(),
  wz: __t.f32(),
  ry: __t.f32(),
  hp: __t.i32(),
  points: __t.i32(),
  online: __t.bool(),
  alive: __t.bool(),
  downed: __t.bool(),
  spectating: __t.bool(),
  lastSeen: __t.timestamp(),
  kills: __t.i32(),
  downs: __t.i32(),
});
export type Player = __Infer<typeof Player>;

export const PowerUp = __t.object("PowerUp", {
  puId: __t.u64(),
  lobbyId: __t.u64(),
  typeIdx: __t.i32(),
  wx: __t.f32(),
  wz: __t.f32(),
  spawnedAt: __t.timestamp(),
});
export type PowerUp = __Infer<typeof PowerUp>;

export const Zombie = __t.object("Zombie", {
  hostZid: __t.u64(),
  lobbyId: __t.u64(),
  zombieType: __t.i32(),
  wx: __t.f32(),
  wz: __t.f32(),
  ry: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  flashLevel: __t.f32(),
  spawnedAt: __t.timestamp(),
});
export type Zombie = __Infer<typeof Zombie>;

export const ZombiePosUpdate = __t.object("ZombiePosUpdate", {
  hostZid: __t.u64(),
  wx: __t.f32(),
  wz: __t.f32(),
  ry: __t.f32(),
  flashLevel: __t.f32(),
});
export type ZombiePosUpdate = __Infer<typeof ZombiePosUpdate>;

