// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  wx: __t.f32(),
  wz: __t.f32(),
  ry: __t.f32(),
  hp: __t.i32(),
  online: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

