// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  hostZid: __t.u64().primaryKey().name("host_zid"),
  zombieType: __t.i32().name("zombie_type"),
  wx: __t.f32(),
  wz: __t.f32(),
  ry: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32().name("max_hp"),
  flashLevel: __t.f32().name("flash_level"),
  spawnedAt: __t.timestamp().name("spawned_at"),
});
